### PR TITLE
Make indicator and geography unique together to fix issue of duplicate Indicator data

### PR DESCRIPTION
**Pull request by goyal1092**
## Description
Issue:
There were duplicate indicator data objects if the user ran task more than once in quick intervals
Fix:
An immediate fix would be to add unique together on geography and indicator so we can not have duplicate indicator data objects and if there is one task will throw an error and will be shown as failed task

## Related Issue
https://wazimap.atlassian.net/browse/WNCM-327

## How to test it locally
Without running the migration open a variable and click save multiple times.
Check for Indicator data count after all task are done processing.
You will see that Indicator data objects are equal to number of geos * the number of time user saved indicator.

Now run migration and try to do this again
In this case user will get exception for one task and one task will return successful message

## Checklist

- [x]  🚀 is the code ready to be merged and go live?
- [x]  🛠 does it work (build) locally

### Pull Request

- [x]  📰 good title
- [x]  📝good description
- [x]  🔖 issue linked
- [x]  📖 changelog filled out

### Commits

- [x]  commits are clean
- [x]  commit messages are clean

### Code Quality

- [x]  🚧 no commented out code
- [x]  🖨 no unnecessary logging
- [x]  🎱 no magic numbers
- [x]  black was run locally (as part of the pre-commit hook)

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

### CODE REVIEW

**Comment by goyal1092** [comment]
Did not add tests as I am not sure how we can write automated tests for this case.
If any reviewer have idea, please let me know :)

**Review by michaelglenister — COMMENTED** [review]
Changes are fine. When testing I couldn't reproduce the problem, I think it could be that the queue ran before I could click again

Could we test using selenium asynchronously to quickly submit two tasks and check if one fails? A race condition could make this difficult

**Comment by goyal1092** [comment]
@michaelglenister It's a bit hard thing to test even in selenium tests. We will have to change cluster config to set sync as False and should have a big enough dataset that it runs at least for a specific period of time and there is no guarantee that the test will pass every time because of race condition

**Comment by emre2038** [comment]
Looks good to me 👍

**Review by emre2038 — APPROVED** [review]
Looks good to me

**Comment by jbothma** [comment]
Merged to master and staging

**Pull request closed without merging**
