### PR TITLE
Added Default Chart Presentation model and data migration to add data

### PR DESCRIPTION
**Pull request by goyal1092**
* Added fk of Default chart presentation to Profile indicator
* Added default_chart_presentation in api and admin panel

@adieyal Please review

* I have added a new model named : DefaultChartPresentation and linked it to profile indicator
* Fk field is currently nullable and is not have default set. Let me know if we want to change that
If value is not selected in PI label & type in api will come as `null`
Screenshot 2020-08-27 at 3 06 05 PM

else:
Screenshot 2020-08-27 at 3 06 47 PM

### CODE REVIEW

**Comment by adieyal** [comment]
> * Added fk of Default chart presentation to Profile indicator
> * Added default_chart_presentation in api and admin panel
> 
> @adieyal Please review
> 
> * I have added a new model named : DefaultChartPresentation and linked it to profile indicator
> * Fk field is currently nullable and is not have default set. Let me know if we want to change that
>   If value is not selected in PI label & type in api will come as `null`
> 
> Screenshot 2020-08-27 at 3 06 05 PM
> 
> else:
> Screenshot 2020-08-27 at 3 06 47 PM

Could you explain the rationale behind the default presentation?

**Comment by goyal1092** [comment]
@adieyal I was not sure how we want to handel the defaults for chart presentation.
Either we can  make `default_chart_presentation` required so user will have to select it in admin or set a default value that will be shown in api if there isn't one selected in PI.

Initially I had to consider this field null to run migration 
If we decide on default value I can add that to migration so older PI do not get affected by it.
Or we can handle it on frontend by setting default there is value is null

Just wanted to push it up and get your views on how should I proceed.

**Comment by adieyal** [comment]
> @adieyal I was not sure how we want to handel the defaults for chart presentation.
> Either we can make `default_chart_presentation` required so user will have to select it in admin or set a default value that will be shown in api if there isn't one selected in PI.
> 
> Initially I had to consider this field null to run migration
> If we decide on default value I can add that to migration so older PI do not get affected by it.
> Or we can handle it on frontend by setting default there is value is null
> 
> Just wanted to push it up and get your views on how should I proceed.

Apologies for my slow responses. Was this a requirement from Jennifer? I haven't yet given much thought to presentations yet. Were you thinking that we might have a dropdown with a list of charts that the Profile Admin can choose from?

**Comment by goyal1092** [comment]
@adieyal Yes, Just like we select choropleth.
We needed a way to select Default chart presentation from Profile Indicator and add that to Profile Indicator api as well.
task : https://trello.com/c/Kb9UXN13/442-allow-for-chart-default-percentage-or-absolute-to-be-set-as-a-config-when-creating-a-profile-indicator-on-the-admin-suite-and-th

**Pull request closed without merging**
