### PR TITLE
Added a new field configuration in profile Indicator model, api & admin

### PR DESCRIPTION
**Pull request by goyal1092**
@adieyal @milafrerichs Please review

## Screenshot
Admin
Admin

is that what you imagined @adieyal?

### CODE REVIEW

**Comment by goyal1092** [comment]
[Allow for chart default (percentage or absolute) to be set as a config when creating a profile indicator on the admin suite and then honoured on the frontend](https://trello.com/c/Kb9UXN13/442-allow-for-chart-default-percentage-or-absolute-to-be-set-as-a-config-when-creating-a-profile-indicator-on-the-admin-suite-and-th)

**Comment by milafrerichs** [comment]
@goyal1092 will do, but can you merge current stagint into this one? thanks.

**Comment by goyal1092** [comment]
Hello @milafrerichs Sorry I did not understand.. 
Do you want me to rebase with PR with current staging branch ?

**Comment by milafrerichs** [comment]
@goyal1092 yes, although no need for a rebase a simple merge commit works as well. 
but if you can yes a rebase would be particularly nice. 

`git merge staging` is sufficient for me though.

**Comment by milafrerichs** [comment]
> @milafrerichs It's already rebased from staging.
> But why do we require git merge ? There is no conflicts in PR's

sorry, my fault. 
I only wanted you to merge in staging to fix the build but my PR where I fixed the travis build is not merged yet. 
will do that tomorrow. 
sorry for the confusion.

**Comment by goyal1092** [comment]
@milafrerichs No worries. 
Thanks :)

**Comment by adieyal** [comment]
@goyal1092 could you please send through an example output from the API?

**Comment by goyal1092** [comment]
Hello @adieyal 
Sorry I missed email for this message.
Currently configuration is empty json. I didn't knew any chart specific configs so I figured that it will be specific to indicator-chart and added manually.

Screenshot 2020-09-11 at 2 02 45 PM (1)

This is screenshot of the config key. It will be  in indicator with as sibling to metadata & choropleth keys.
If you can let me know if there is any default chart configuration that we should have in our configuration key I will add that to PR.

**Comment by goyal1092** [comment]
I see that mila has made some changes for changing key from `configuration` to `chart_configuaration`.
will update latest api response here for this in an hour.
Thank

**Review by milafrerichs — APPROVED** [review]
going to merge this now but needs a test next week.

**Pull request merged**
