### PR TITLE
issue 194 -It should be possible to update the universe of a variable from the django admin

### PR DESCRIPTION
**Pull request by Faysalali534**
## Description
Made possible to update the universe of a variable from the django admin

## Related Issue
[Issue](https://github.com/OpenUpSA/wazimap-ng/issues/194)
### Updated
Query for fetching all data in django builtin `get_form` for change view and add view
## Checklist

- [ ]  🚀 is the code ready to be merged and go live?
- [ ]  🛠 does it work (build) locally

### Pull Request

- [ ]  📰 good title
- [ ]  📝good description
- [ ]  🔖 issue linked
- [ ]  📖 changelog filled out

### Commits

- [ ]  commits are clean
- [ ]  commit messages are clean

### Code Quality

- [ ]  🚧 no commented out code
- [ ]  🖨 no unnecessary logging
- [ ]  🎱 no magic numbers
- [ ]  black was run locally (as part of the pre-commit hook)

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

### CODE REVIEW

**Review by milafrerichs — CHANGES_REQUESTED** [review]
you were not able to try this out locally right? because this does not make it possible to change the universe.

**Comment by Faysalali534** [comment]
This is working locally as expected. Let me attach a video how it is working on my end. Lets see if I'm missing something.

**Comment by Faysalali534** [comment]
@milafrerichs  have a look to it https://www.loom.com/share/c64b6dad9a2948c790bc5d601671a18f

**Comment by milafrerichs** [comment]
the issue is about **updating** it. the description may not be 100% clear, but it's about editing a variable.
so if you create a new one, sure it's possible to select a universe. but it's about updating it on an existing one.

**Comment by Faysalali534** [comment]
Okay got it now. Thanks for making it more clear. Description was little unclear as per your ticket expectations. I will make it that way and will let you know.

**Comment by Faysalali534** [comment]
@milafrerichs  here is the link to video after changes https://www.loom.com/share/ad3fd39ddff74cd09c03aca72c1f00a9

**Pull request closed without merging**
